package net.dogs.remote.ir

import android.content.Context
import org.json.JSONObject

/** One rendered button: carrier frequency + raw on/off microsecond pattern. */
data class IrButton(
    val id: String,
    val freqHz: Int,
    /** Alternating on/off durations in microseconds, starting with ON. */
    val pattern: IntArray,
    val proto: String,
    val device: Int,
    val subdevice: Int,
    val function: Int,
)

data class IrVariant(
    val id: String,
    val label: String,
    /** false = timings inferred, not yet confirmed on a real device. */
    val verified: Boolean,
    val sourceCsv: String,
    val buttons: Map<String, IrButton>,
)

data class IrBrand(val name: String, val variants: List<IrVariant>)

data class IrDatabase(
    val brands: List<IrBrand>,
    /** Variant ids in the order Magic Mode tries them (Samsung first). */
    val magicOrder: List<String>,
) {
    val variantsById: Map<String, IrVariant> =
        brands.flatMap { it.variants }.associateBy { it.id }
    val magicVariants: List<IrVariant> = magicOrder.mapNotNull { variantsById[it] }
}

/** Loads the audited database generated by tools/gen_ir_db.py. */
fun loadIrDatabase(context: Context): IrDatabase {
    val text = context.assets.open("ir_database.json").bufferedReader().readText()
    val root = JSONObject(text)

    val brands = mutableListOf<IrBrand>()
    val brandArr = root.getJSONArray("brands")
    for (i in 0 until brandArr.length()) {
        val b = brandArr.getJSONObject(i)
        val variants = mutableListOf<IrVariant>()
        val varArr = b.getJSONArray("variants")
        for (j in 0 until varArr.length()) {
            val v = varArr.getJSONObject(j)
            val buttons = mutableMapOf<String, IrButton>()
            val btnObj = v.getJSONObject("buttons")
            val keys = btnObj.keys()
            while (keys.hasNext()) {
                val key = keys.next()
                val d = btnObj.getJSONObject(key)
                val pArr = d.getJSONArray("pattern")
                val pattern = IntArray(pArr.length()) { k -> pArr.getInt(k) }
                // Defensive: never hand a malformed pattern to the emitter.
                if (pattern.isNotEmpty() && pattern.all { it > 0 }) {
                    buttons[key] = IrButton(
                        id = key,
                        freqHz = d.getInt("freq"),
                        pattern = pattern,
                        proto = d.getString("proto"),
                        device = d.getInt("dev"),
                        subdevice = d.getInt("sub"),
                        function = d.getInt("fun"),
                    )
                }
            }
            variants += IrVariant(
                id = v.getString("id"),
                label = v.getString("label"),
                verified = v.getBoolean("verified"),
                sourceCsv = v.getString("source_csv"),
                buttons = buttons,
            )
        }
        brands += IrBrand(name = b.getString("brand"), variants = variants)
    }

    val orderArr = root.getJSONArray("magic_order")
    val magicOrder = List(orderArr.length()) { orderArr.getString(it) }
    return IrDatabase(brands, magicOrder)
}
