package net.dogs.remote.ir

import android.content.Context
import android.util.Log
import org.json.JSONObject

/** One rendered button: carrier frequency + raw on/off microsecond pattern. */
data class IrButton(
    val id: String,
    val freqHz: Int,
    /** Alternating on/off durations in microseconds, starting with ON. */
    val pattern: IntArray,
    val proto: String,
    val device: Int,
    val subdevice: Int,
    val function: Int,
)

data class IrVariant(
    val id: String,
    val label: String,
    /** false = timings inferred, not yet confirmed on a real device. */
    val verified: Boolean,
    val sourceCsv: String,
    val buttons: Map<String, IrButton>,
)

data class IrBrand(val name: String, val variants: List<IrVariant>)

data class IrDatabase(
    val brands: List<IrBrand>,
    /** Variant ids in the order Magic Mode tries them (Samsung first). */
    val magicOrder: List<String>,
) {
    val variantsById: Map<String, IrVariant> =
        brands.flatMap { it.variants }.associateBy { it.id }
    val magicVariants: List<IrVariant> = magicOrder.mapNotNull { variantsById[it] }
}

/** Loads the audited database generated by tools/gen_ir_db.py.
 *
 * Read-path hardening: the asset is missing or its JSON is malformed,
 * [loadIrDatabase] returns an empty database instead of throwing —
 * [RemoteViewModel] builds from it at init, so a throw here would crash the
 * app at startup. Individual brands/variants/buttons are parsed
 * independently, so one bad entry can't nuke the rest. The UI already treats
 * an empty database as "no remotes available", so the app stays usable and
 * the failure is logged for diagnosis.
 */
fun loadIrDatabase(context: Context): IrDatabase {
    val text = try {
        context.assets.open("ir_database.json").bufferedReader().readText()
    } catch (t: Throwable) {
        Log.w(TAG, "IR database asset missing or unreadable — starting empty", t)
        return IrDatabase(emptyList(), emptyList())
    }
    return try {
        parseIrDatabase(JSONObject(text))
    } catch (t: Throwable) {
        Log.w(TAG, "IR database JSON corrupt — starting empty", t)
        IrDatabase(emptyList(), emptyList())
    }
}

/**
 * Pure parse of the database JSON. Kept separate from the asset read so the
 * read-path contract is testable without Android tooling.
 */
internal fun parseIrDatabase(root: JSONObject): IrDatabase {
    val brands = mutableListOf<IrBrand>()
    val seenVariantIds = mutableSetOf<String>()
    val brandArr = root.optJSONArray("brands") ?: return IrDatabase(emptyList(), emptyList())
    for (i in 0 until brandArr.length()) {
        val b = brandArr.optJSONObject(i) ?: continue
        val brandName = b.optString("brand").takeIf { it.isNotBlank() } ?: continue
        val variants = mutableListOf<IrVariant>()
        val varArr = b.optJSONArray("variants")
        if (varArr != null) {
            for (j in 0 until varArr.length()) {
                try {
                    val v = varArr.optJSONObject(j) ?: continue
                    val variantId = v.optString("id").takeIf { it.isNotBlank() } ?: continue
                    // Duplicate ids would silently collapse in associateBy — keep the first.
                    if (!seenVariantIds.add(variantId)) continue
                    variants += IrVariant(
                        id = variantId,
                        label = v.optString("label", variantId),
                        verified = v.optBoolean("verified", false),
                        sourceCsv = v.optString("source_csv"),
                        buttons = parseIrButtons(v.optJSONObject("buttons")),
                    )
                } catch (t: Throwable) {
                    // One malformed variant must not nuke the rest.
                    Log.w(TAG, "skipping malformed IR variant", t)
                }
            }
        }
        brands += IrBrand(name = brandName, variants = variants)
    }

    val magicOrder = mutableListOf<String>()
    val orderArr = root.optJSONArray("magic_order")
    if (orderArr != null) {
        for (i in 0 until orderArr.length()) {
            val id = orderArr.optString(i).trim()
            // Blank, duplicate, or unknown ids are skipped; IrDatabase
            // resolves magicOrder through variantsById so missing ids
            // already can't break magic mode.
            if (id.isNotEmpty() && id !in magicOrder) magicOrder += id
        }
    }
    return IrDatabase(brands, magicOrder)
}

/**
 * Parse one variant's button map. Every value is validated: blank ids are
 * dropped, carrier frequencies must sit in the realistic IR band
 * ([IR_FREQ_MIN_HZ]–[IR_FREQ_MAX_HZ]), patterns must be non-empty, bounded in
 * length, and contain only positive on/off durations — the emitter rejects
 * anything else, so malformed entries never reach it.
 */
private fun parseIrButtons(btnObj: JSONObject?): Map<String, IrButton> {
    val buttons = mutableMapOf<String, IrButton>()
    if (btnObj == null) return buttons
    val keys = btnObj.keys()
    while (keys.hasNext()) {
        val key = keys.next()
        if (key.isBlank()) continue
        try {
            val d = btnObj.optJSONObject(key) ?: continue
            val freqHz = d.optInt("freq", -1)
            if (freqHz !in IR_FREQ_MIN_HZ..IR_FREQ_MAX_HZ) continue
            val pArr = d.optJSONArray("pattern") ?: continue
            if (pArr.length() == 0 || pArr.length() > IR_PATTERN_MAX_WORDS) continue
            val pattern = IntArray(pArr.length()) { k -> pArr.optInt(k, -1) }
            // Defensive: never hand a malformed pattern to the emitter.
            if (pattern.any { it <= 0 }) continue
            buttons[key] = IrButton(
                id = key,
                freqHz = freqHz,
                pattern = pattern,
                proto = d.optString("proto"),
                device = d.optInt("dev", -1),
                subdevice = d.optInt("sub", -1),
                function = d.optInt("fun", -1),
            )
        } catch (t: Throwable) {
            Log.w(TAG, "skipping malformed IR button", t)
        }
    }
    return buttons
}

private const val TAG = "IrDatabase"
/** Real IR carrier frequencies live between 10 kHz and 100 kHz. */
internal const val IR_FREQ_MIN_HZ = 10_000
internal const val IR_FREQ_MAX_HZ = 100_000
/** Longest pattern in the shipped database is a few hundred words; 10k is a sane ceiling. */
internal const val IR_PATTERN_MAX_WORDS = 10_000
